name: build

on: [push, pull_request]

env:
  CI: "1"

# Taken from https://github.com/swc-project/swc/blob/master/.github/workflows/cargo.yml

jobs:
  lint:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stuff
        run: rustup component add rustfmt clippy
      - name: Run cargo clippy
        run: cargo clippy -- -Dwarnings
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Ensure that all components all compilable.
      - name: Run cargo check for all targets
        run: cargo check --color always --all --all-targets

      - name: Run cargo test
        run: cargo test --color always --all
